### ISSUE TITLE
global ordering:false not working why?

### ISSUE THREAD

**Issue by saahmadi** [darrachequesne/spring-data-jpa-datatables#107]
global ordering:false not working why?

**Comment by smsotirov** [comment]
I have the same issue. basically, whet this is set, the request does nto contains any rder. So there is not order[0].column... and order[0].dir and order[0].name params in the request. While the validation in DataTablesInput is @NotEmpty for the field "order". I don't have a fix to this issue. I'm thinking to create my implemetation of the whole project because of this issue.

**Comment by darrachequesne** [comment]
This should be fixed by https://github.com/darrachequesne/spring-data-jpa-datatables/commit/a214d5bb199fff4ccd578c3bbb71ee64f3a0f198, included in version [`6.0.2`](https://github.com/darrachequesne/spring-data-jpa-datatables/releases/tag/v6.0.2).
